version: '3'

services:
  redis:
    image: 'redis:alpine'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: app
    stdin_open: true
    tty: true
    expose:
      - '8000'
    command: gunicorn --reload myproject.wsgi:application -b 0.0.0.0:8000
    depends_on:
      - redis

  nginx:
    image: nginx
    hostname: nginx
    ports:
      - '80:8000'
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - app

  celery:
    image: celery:latest
    command: "mkdir myproject && celery -A myproject --port=8000 worker -l info --queue=fila1"
    volumes:
      - .:./myproject
    depends_on:
      - app
      - redis
