version: '3.7'

services:
  db:
    image: postgres:11-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      # - .env:/app/.env
    env_file:
      - .env
    # environment:
    #   POSTGRES_DB: example
    #   POSTGRES_USER: example
    #   POSTGRES_PASSWORD: example
    networks:
      - fullstack

  redis:
    image: 'redis:alpine'
    hostname: redis
    networks:
      - fullstack

  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    hostname: app
    stdin_open: true
    expose:
      - '8000'
    volumes:
      - .env:/app/.env
    command: bash -c "python manage.py migrate && gunicorn myproject.wsgi:application -b 0.0.0.0:8000"
    depends_on:
      - redis
      - db
    networks:
      - fullstack

  nginx:
    image: nginx
    hostname: nginx
    ports:
      - '8000:8000'
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - fullstack

  celery:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: "celery -A myproject worker -l info --queue=fila1"
    depends_on:
      - app
      - redis
      - db
    networks:
      - fullstack

  flower:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: "celery -A myproject flower"
    depends_on:
      - celery
    networks:
      - fullstack

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    hostname: vuejs
    ports:
      - '80:8080'
    depends_on:
      - app
      - db
    networks:
      - fullstack

volumes:
  pgdata:

networks:
  fullstack: