version: '3.7'

services:
  redis:
    image: 'redis:alpine'
    hostname: redis
    networks:
      - fullstack

  app:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: app
    stdin_open: true
    expose:
      - '8000'
    volumes:
      - .env:/app/.env
    command: bash -c "gunicorn myproject.wsgi:application -b 0.0.0.0:8000"
    depends_on:
      - redis
    networks:
      - fullstack

  nginx:
    image: nginx
    hostname: nginx
    ports:
      - '8000:8000'
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - fullstack

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: "celery -A myproject worker -l info --queue=fila1"
    depends_on:
      - app
      - redis
    networks:
      - fullstack

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    command: "celery -A myproject flower"
    depends_on:
      - celery
    networks:
      - fullstack

  frontend:
    build:
      context: .
      dockerfile: DockerfileVueJS
    hostname: vuejs
    ports:
      - '80:8080'
    networks:
      - fullstack

networks:
  fullstack: